### ISSUE TITLE
This forum has a large number of xss vulnerabilities

### ISSUE THREAD

**Issue by retnullyu** [atjiu/pybbs#171]
## The first is located at the home page search
Enter in the search box`11" onclick='alert(/xss/)'`
![image](https://user-images.githubusercontent.com/51900604/149858294-9fdb13ca-5575-44d3-9c93-b8a4c0f7f6a1.png)
## The second vulnerability is located in the backend
In the topic editor in the background, enter`<img src=1 onerror=alert(/xss/)>`
![image](https://user-images.githubusercontent.com/51900604/149864571-cbbd7680-a3f6-415c-9c20-3ba09cd1aa60.png)
![image](https://user-images.githubusercontent.com/51900604/149864688-cd20e4ab-91b0-4351-8888-753e0b49aa0b.png)
## The third vulnerability is located at the topic search
Enter in the search box `" onmouseover='alert(/xss/)'`
![image](https://user-images.githubusercontent.com/51900604/149864885-fece0b09-8671-4829-8c37-f7ac14acab0e.png)
## and many more
...

**Comment by atjiu** [comment]
感谢，稍微修复了一些
其实后台的输入框应该不用防的，后台是内部人员使用来管理论坛内容的，总不会自己去注入自己的网站吧 😄 

搜索框，发布话题的标题框我都做处理了
