### ISSUE TITLE
主题选择失败

### ISSUE THREAD

**Issue by cherryxyz** [atjiu/pybbs#176]
如图所示，下拉选不了

![image](https://user-images.githubusercontent.com/18420682/163497542-4f80d399-961c-46c5-80da-b9e6fb70c187.png)

**Comment by cherryxyz** [comment]
选不了simple主题

**Comment by atjiu** [comment]
simple主题是要加载插件的

如果你会打包插件jar包，则可参见 [spring-boot 项目利用spring切面实现插件功能，对项目无侵入](https://atjiu.github.io/2019/07/02/spring-boot-plugin/) 来实现

如果你不会打包插件jar包，可将项目根目录下的 `plugins/theme-simple-plugin/src` 所有文件都复制到 `pybbs/src` 下，再重启项目应该也能实现
