### ISSUE TITLE
中文搜索bug

### ISSUE THREAD

**Issue by ZhangYiQiu** [atjiu/pybbs#179]
搜索中文后，输入框变成\u开头的经过编码的字符
search?keyword=测试
![image](https://user-images.githubusercontent.com/22910338/163957920-6915293f-3868-430a-8740-cfd4f406eead.png)

**Comment by atjiu** [comment]
测试了一下，没有复现
![image](https://github.com/atjiu/pybbs/assets/6915570/4be3d6c5-be5a-479f-873c-343975356881)
