### ISSUE TITLE
There is an arbitrary administrator operation vulnerability in xss and csrf

### ISSUE THREAD

**Issue by boluo123432423** [atjiu/pybbs#184]
In comment on：
![image](https://user-images.githubusercontent.com/107671675/223609264-2e6de4d6-a454-401a-a939-a4094b37ac9a.png)
In src/main/java/co/yiiu/pybbs/controller/api/CommentApiController.java, only sensitive keywords are filtered
![image](https://user-images.githubusercontent.com/107671675/223609483-849652f6-fa7a-4a97-8eaf-ce4e4a13d557.png)
The src/main/resources/templates/admin/comment/list.ftl parameter is not filtered
![image](https://user-images.githubusercontent.com/107671675/223610245-4aef023c-e7f7-4f75-96a2-6e3721f7f859.png)
Cooperate with csrf ，Review payload
View comments in the background：
![image](https://user-images.githubusercontent.com/107671675/223610741-c9a265d0-48ba-4ce5-906c-a071add635c1.png)
Payload triggered
![image](https://user-images.githubusercontent.com/107671675/223610939-4a5687d9-eb66-4661-8b74-3a00e0cb85b1.png)
![image](https://user-images.githubusercontent.com/107671675/223610960-47670218-6cba-425a-b2ac-888cccbbac74.png)

Temporary repair suggestions：

In src/main/resources/templates/admin/comment/list.ftl 56:
Modify to:
<td colspan="5">${model.formatContent(comment.content)}</td>

Vulnerability submission information
author：boluo5100
mail：[basiclearn@163.com](mailto:basiclearn@163.com)

**Comment by atjiu** [comment]
thank you!
