### ISSUE TITLE
想用MariaDB代替mysql，有可行方案吗？

### ISSUE THREAD

**Issue by leeseean** [atjiu/pybbs#187]
需要修改哪些内容？

**Comment by atjiu** [comment]
我没用过MariaDB，不知道与MySQL的语法有什么区别

关于SQL语句可能会有影响的地方：

1. flyway执行的sql脚本
2. mapper中的sql语句

你可以尝试切换一下，如果有问题，要么是SQL语句的问题，要么是MyBatis的问题，排查一下吧
