### ISSUE TITLE
fastjson <= 1.2.80 反序列化任意代码执行漏洞

### ISSUE THREAD

**Issue by tryantdb** [atjiu/pybbs#190]
来自阿里云漏洞扫描告警。
漏洞引入来源：
        <justauth.version>1.15.5</justauth.version>
        
        <dependency>
            <groupId>me.zhyd.oauth</groupId>
            <artifactId>JustAuth</artifactId>
            <version>${justauth.version}</version>
        </dependency>
建议升级JustAuth到fastjson >= 1.2.80的版本
例如：https://mvnrepository.com/artifact/me.zhyd.oauth/JustAuth/1.16.6

**Comment by atjiu** [comment]
我已经将fastjson相关代码都删了，但justauth里还是有，至于项目版本号就不升了，不知道升了后会不会有什么奇怪的bug产生。

如果你用不到第三方登录，可以打开pom.xml搜到justauth依赖位置，按照注释将fastjson给排除掉即可

    
        <dependency>
            <groupId>me.zhyd.oauth</groupId>
            <artifactId>JustAuth</artifactId>
            <version>${justauth.version}</version>
            
            
        </dependency>
