### ISSUE TITLE
Vulnerability Alert

### ISSUE THREAD

**Issue by cxcxcxcxcxcxcxc** [atjiu/pybbs#191]
The `username` is controllable and has no filtering, allowing for directory traversal.

![image](https://github.com/user-attachments/assets/b482b501-e239-4eec-a9a9-058766726afc)

**Comment by atjiu** [comment]
在IndexApiController的100行做了验证

https://github.com/atjiu/pybbs/blob/714b1bbc17938de0bef1bb3320868ba0457a422f/src/main/java/co/yiiu/pybbs/controller/api/IndexApiController.java#L100
