### ISSUE TITLE
是否有目录功能的支持？

### ISSUE THREAD

**Issue by saaspeter** [atjiu/pybbs#192]
Java开源论坛不多，这个项目很棒，清爽，看得明白，样式大部分支持手机review。

目前感觉缺少目录的支持，一般论坛都有目录：category。希望能支持模块创建或在后台创建。

**Comment by atjiu** [comment]
项目中的标签就是你说的目录功能，在后台编辑话题可创建标签

**Comment by saaspeter** [comment]
感谢回复，感觉Tag标签是在创建话题topic的时候创建的，但在创建topic的UI上并没有看到tag的输入框，后台api好像是支持的。另外个人觉得category和tags是不同的，category是大的目录，例如对于健康论坛来说，顶级目录可以是：疾病圈子，健康感悟、药物说明等，而在每个category下可能还有子目录，这个最好是由Admin来创建管理。而tags更像是在一个目录中的一类问题的集合，可以认为是小目录，可以由用户自由输入。当然有的博客系统是没有目录的，例如知乎，但对于很多论坛是要有一个目录的，例如小米的论坛是以手机型号为目录的。

**Comment by saaspeter** [comment]
got, 谢谢解释。
