### ISSUE TITLE
user.token security issue

### ISSUE THREAD

**Issue by saaspeter** [atjiu/pybbs#193]
Hi:
 
      你好，我看到在页面点击登录后调用“/api/login”接口，这个接口中直接把user表中的token值拿出来存入cookie中了。而token的刷新好像是在页面上点击刷新token才做刷新的。这样只要拿到这个token就可以伪造登录了，直到用户自己手动刷新这个token。

      推荐的做法是登录的时候生成新的真随机的cookie，长度也不能太短，把这个随机值存在db中和user_id对应，然后再把这个值写入cookie，带有默认时间。检查cookie的时候要检查是否超时。（如果需要长时间登录，需要再写入一个remember me cookie）

       另外，/api/**开头的api好像都没有做权限验证，postman可以直接call通。

**Comment by atjiu** [comment]
感谢反馈，针对你说的两点问题我解释一下

1. 你推荐的做法其实跟我直接拿用户的token写到cookie本质是一样的
2. /api/ 下的部分接口是无需token的，确实能直接访问
